# Cluster Autoscaler 기본 설정 예시 (EKS, IRSA 사용하는 경우)
autoDiscovery:
  clusterName: {{ .Release.Namespace | default "default" }}

awsRegion: ap-northeast-2         # 서울 리전이면 ap-northeast-2, 도쿄면 ap-northeast-1 등 리전에 맞게 변경
rbac:
  create: true
cloudProvider: aws

# IRSA(IAM Role for Service Account)로 자동 권한 할당하려면 아래 사용
# serviceAccount:
#   create: true
#   name: cluster-autoscaler
#   annotations: {}
#   eks.amazonaws.com/role-arn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/<YOUR_CLUSTER_AUTOSCALER_ROLE>

