name: AWS Nuke

on:
  workflow_dispatch:

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install aws-nuke
        run: |
          curl -L -o aws-nuke.tar.gz https://github.com/rebuy-de/aws-nuke/releases/download/v2.24.0/aws-nuke-v2.24.0-linux-amd64.tar.gz
          tar -xzf aws-nuke.tar.gz
          chmod +x aws-nuke-v2.24.0-linux-amd64
          sudo mv aws-nuke-v2.24.0-linux-amd64 /usr/local/bin/aws-nuke

      - name: Create config.yml from Base64 secret
        run: |
          echo "${{ secrets.NUKE_CONFIG_B64 }}" | base64 -d > config.yml

      - name: Debug config.yml (마스킹돼도 괜찮음)
        run: |
          echo "====== config.yml (GitHub Secret 기반) ======"
          cat -A config.yml


      - name: AWS Nuke 실제 삭제
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws-nuke --config config.yml --no-dry-run --force
