name: Terraform Deploy (No S3 Backend)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-seoul:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION || 'ap-northeast-2' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Extract Output (ALB DNS)
      id: output
      run: |
        echo "ALB_DNS=$(terraform output -raw alb_dns)" >> $GITHUB_ENV

    - name: Use Output
      run: echo "▶ 배포된 ALB 주소는: $ALB_DNS"
