name: Terraform Deploy (No S3 Backend)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Configure kubeconfig for EKS Seoul
      run: |
        aws eks update-kubeconfig \
          --region ap-northeast-2 \
          --name myapp-seoul \
          --kubeconfig ./kubeconfig-seoul

    - name: Configure kubeconfig for EKS Tokyo
      run: |
        aws eks update-kubeconfig \
          --region ap-northeast-1 \
          --name myapp-tokyo \
          --kubeconfig ./kubeconfig-tokyo

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      continue-on-error: true
      
    - name: Upload Terraform State
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tfstate
        path: terraform.tfstate

  destroy:
    needs: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

    steps:
    - name: Wait 2 minutes before destroy
      run: sleep 120

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Download tfstate
      uses: actions/download-artifact@v4
      with:
        name: tfstate
        path: ./tfstate

    - name: Move tfstate into place
      run: mv ./tfstate/terraform.tfstate terraform.tfstate

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
