name: Terraform Destroy - VPC only

on:
  workflow_dispatch:

jobs:
  destroy-vpc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Download Terraform State
      uses: actions/download-artifact@v4
      with:
        name: tfstate-seoul

    - name: Move tfstate to working directory
      run: mv tfstate-seoul/terraform.tfstate terraform.tfstate

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy - VPC only
      run: terraform destroy -auto-approve -target=module.seoul_vpc
