name: Terraform Apply - VPC only

on:
  workflow_dispatch:

jobs:
  apply-vpc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan - VPC only
      run: terraform plan -target=module.seoul_vpc -out=tfplan-vpc

    - name: Terraform Apply - VPC only
      run: terraform apply -auto-approve tfplan-vpc

    - name: Save Terraform State (for destroy)
      uses: actions/upload-artifact@v4
      with:
        name: tfstate-seoul
        path: terraform.tfstate
