name: Terraform Apply - VPC only

on:
  workflow_dispatch:

jobs:
  test-vpc:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan - VPC only
      run: terraform plan -target=module.seoul_vpc -out=tfplan-vpc

    - name: Terraform Apply - VPC only
      run: terraform apply -target=module.seoul_vpc -auto-approve

    - name: Save Terraform State (for destroy)
      uses: actions/upload-artifact@v4
      with:
        name: tfstate-seoul
        path: terraform.tfstate
