name: Terraform VPC Apply or Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: apply or destroy'
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

jobs:
  vpc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Download tfstate for destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      uses: actions/download-artifact@v4
      with:
        name: tfstate-seoul

    - name: Move tfstate to current directory
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: mv tfstate-seoul/terraform.tfstate terraform.tfstate

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (Apply only)
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform plan -target=module.seoul_vpc -out=tfplan-vpc

    - name: Terraform Apply (Apply only)
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve tfplan-vpc

    - name: Save tfstate for destroy
      if: ${{ github.event.inputs.action == 'apply' }}
      uses: actions/upload-artifact@v4
      with:
        name: tfstate-seoul
        path: terraform.tfstate

    - name: Terraform Destroy (Destroy only)
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -auto-approve -target=module.seoul_vpc
