name: Terraform VPC Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -target=module.seoul_vpc -out=tfplan-vpc

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan-vpc

    - name: Save tfstate for destroy
      uses: actions/upload-artifact@v4
      with:
        name: tfstate-seoul
        path: terraform.tfstate
